#!/usr/bin/env python3
"""Build journal-ready Monte Carlo tables from ``outputs/sim/*.jsonl``.

The revised MC schema stores truth, estimates, White/diagonal inference,
spatial-kernel inference, rank-selection metadata, and fold-retention diagnostics.
This script re-aggregates JSONL checkpoints with :func:`dlrhcs.mc.aggregate` and
writes CSV plus LaTeX fragments to ``outputs/sim/tables/``.
"""
from __future__ import annotations

import csv
import json
import math
import os
import re
import sys
from glob import glob

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from dlrhcs.mc import aggregate  # noqa: E402

SIM = os.path.join(ROOT, "outputs", "sim")
OUT = os.path.join(SIM, "tables")
PAPER_TABLES = os.path.join(ROOT, "tables")

TARGET_OBJECT = {"lag": "lag", "slope": "covariate"}
TARGET_TYPE = {
    "entry": "entry",
    "gmean": "group mean",
    "fmean": "full mean",
    "contrast": "contrast",
}

PAPER_TARGET_LABELS = {
    "lag entry": "AR entry",
    "lag group mean": "AR group mean",
    "lag full mean": "AR full mean",
    "lag contrast": "AR group contrast",
    "covariate entry": "Slope entry",
    "covariate group mean": "Slope group mean",
    "covariate full mean": "Slope full mean",
    "covariate contrast": "Slope group contrast",
}

PERFORMANCE_TABLE_NOTE = (
    "DGP 1 reports diagonal/White inference. DGP 2--3 report spatial-kernel "
    "inference with a Bartlett kernel on the lattice distance |i-j| and "
    "bandwidth h_N=floor(N^(1/3)). Entry targets use "
    "i*=floor(N/2)+1 and t*=floor(T/2)+1. Group 1 is the first half of units, "
    "Group 0 is the second half, and contrasts are Group 1 mean minus Group 0 mean."
)

MAIN_PERFORMANCE_TABLE_NOTE = (
    "Coverage is the empirical frequency with which the nominal 95 percent "
    "confidence interval contains the true target value. DGP 1 reports "
    "diagonal/White inference. DGP 2--3 report spatial-kernel inference with a "
    "Bartlett kernel on the lattice distance |i-j| and bandwidth "
    "h_N=floor(N^(1/3)). Entry targets use i*=floor(N/2)+1 and "
    "t*=floor(T/2)+1. Group 1 is the first half of units, Group 0 is the "
    "second half, and contrasts are Group 1 mean minus Group 0 mean."
)

FULL_PERFORMANCE_TABLE_NOTE = (
    "Size is the empirical rejection frequency for the nominal 5 percent "
    "two-sided test, and coverage is the empirical frequency with which the "
    "nominal 95 percent confidence interval contains the true target value. "
    "DGP 1 reports diagonal/White inference. DGP 2--3 report spatial-kernel "
    "inference with a Bartlett kernel on the lattice distance |i-j| and "
    "bandwidth h_N=floor(N^(1/3))."
)

FOLD_RETENTION_TABLE_NOTE = (
    "This table reports cross-fitting quantities only. The spatial-kernel "
    "bandwidth $h_N$ does not affect the retained training shares. For DGPs "
    "2--3, inference uses Bartlett spatial-kernel standard errors with "
    "$h_N=\\lfloor N^{1/3}\\rfloor$. The quantity $q_T$ is the time buffer "
    "used in cross-fitting, and $r_N$ is the unit or spatial buffer. The "
    "quantity $J$ is the realized number of folds generated by the finite-fold "
    "rule unless manually overridden. ``Retained non-validation'' is the "
    "average share of non-validation cells remaining after buffer deletion. "
    "``Retained total'' is the average number of retained training cells "
    "divided by the total number of cells, $NT$. The retained shares are "
    "averaged over the realized scattered-fold assignments and production "
    "replications. Consequently, small differences across runs or master seeds "
    "are expected before rounding."
)


def fmt(x, d=3):
    """Format numbers without leading plus signs; return -- for missing values."""
    if x is None or x == "":
        return "--"
    try:
        xx = float(x)
    except (TypeError, ValueError):
        return str(x)
    if not np.isfinite(xx):
        return "--"
    return f"{xx:.{d}f}"


def _latex_escape(x):
    return str(x).replace("_", r"\_")


def _rank_str(rank):
    if rank is None:
        return "--"
    return "(" + ",".join(str(int(x)) for x in rank) + ")"


def _dgp_label(dgp):
    key = str(dgp or "unknown").lower()
    labels = {"dgp1": "DGP 1", "dgp2": "DGP 2", "dgp3": "DGP 3", "legacy": "legacy"}
    return labels.get(key, str(dgp or "unknown"))


def _target_label(name):
    if "_" not in name:
        return name
    obj, kind = name.split("_", 1)
    return f"{TARGET_OBJECT.get(obj, obj)} {TARGET_TYPE.get(kind, kind)}"


def _paper_target_label(label):
    return PAPER_TARGET_LABELS.get(str(label), str(label))


EXCLUDED_JSONL_PREFIXES = ("tmp_", "smoke_", "test_")
REPORT_JSONL_PREFIXES = ("grid_", "grid_v2_", "rank_")
ALLOW_PARTIAL_PRODUCTION = False
_LAST_DROPPED_DUPLICATE_JSONL = []
_LAST_EXCLUDED_INCOMPLETE_JSONL = []

ACTIVE_MANUSCRIPT_TEX = {
    "tab_mc_main_summary.tex",
    "tab_mc_perf_dgp1.tex",
    "tab_mc_perf_dgp2.tex",
    "tab_mc_perf_dgp3.tex",
    "tab_mc_rank.tex",
    "tab_mc_coeff_summary.tex",
    "tab_mc_folds.tex",
    "tab_mc_opt.tex",
}

OBSOLETE_OUTPUT_TEX = {
    "tab_mc_performance.tex",
    "tab_mc_performance_current.tex",
    "tab_mc_performance_full.tex",
    "tab_fold_retention.tex",
    "tab_rank_frequency.tex",
}


def _is_report_jsonl(path):
    base = os.path.basename(path)
    if base.startswith(EXCLUDED_JSONL_PREFIXES):
        return False
    return base.startswith(REPORT_JSONL_PREFIXES)


def _report_file_kind(path):
    base = os.path.basename(path)
    if base.startswith("grid_v2_"):
        return "grid_v2"
    if base.startswith("grid_"):
        return "grid"
    if base.startswith("rank_"):
        return "rank"
    return "other"


def _schema_source(item):
    kind = _report_file_kind(item["path"])
    if kind == "grid_v2":
        return "grid_v2"
    if kind == "grid":
        return "old grid"
    if kind == "rank":
        return "rank"
    return kind


def _as_bool(value, default=False):
    if value is None:
        return bool(default)
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, np.integer)):
        return bool(value)
    text = str(value).strip().lower()
    if text in {"1", "true", "t", "yes", "y"}:
        return True
    if text in {"0", "false", "f", "no", "n"}:
        return False
    return bool(default)


def _rank_tuple(value):
    if value in (None, ""):
        return None
    if isinstance(value, str):
        parts = [part.strip() for part in value.replace("(", "").replace(")", "").split(",")]
        try:
            return tuple(int(part) for part in parts if part != "")
        except ValueError:
            return (value,)
    try:
        return tuple(int(part) for part in value)
    except TypeError:
        try:
            return (int(value),)
        except (TypeError, ValueError):
            return (str(value),)


def _rank_cell(value):
    rank = _rank_tuple(value)
    if rank is None:
        return ""
    return _rank_str(rank)


def _int_meta(meta, *keys):
    for key in keys:
        value = meta.get(key)
        if value not in (None, ""):
            return int(value)
    return None


def _available(meta, *keys):
    for key in keys:
        value = meta.get(key)
        if value in (None, ""):
            continue
        if isinstance(value, (float, np.floating)):
            if not np.isfinite(float(value)):
                continue
        return True
    return False


def _duplicate_cell_key(item):
    meta = item["meta"]
    kind = _report_file_kind(item["path"])
    select = _as_bool(meta.get("select"), default=(kind == "rank"))
    if select:
        mode = (
            "rank-selection",
            _rank_tuple(meta.get("true_ranks", meta.get("true_ranks_from_records"))),
            _rank_tuple(meta.get("rank_caps")),
        )
    else:
        mode = (
            "fixed-rank",
            _rank_tuple(meta.get("fixed_ranks", meta.get("selected_ranks_first_record"))),
        )
    return (
        str(meta.get("dgp_type", "")).lower(),
        _int_meta(meta, "N"),
        _int_meta(meta, "Tp", "T"),
        bool(select),
        mode,
    )


def _resolve_duplicate_cells(items):
    """Prefer complete grid_v2 over grid for the same fixed-rank production cell."""
    grouped = {}
    passthrough = []
    for item in items:
        kind = _report_file_kind(item["path"])
        select = _as_bool(item["meta"].get("select"), default=(kind == "rank"))
        if kind in {"grid", "grid_v2"} and not select:
            grouped.setdefault(_duplicate_cell_key(item), []).append(item)
        else:
            passthrough.append(item)

    kept = list(passthrough)
    dropped = []
    for group in grouped.values():
        has_v2 = any(_report_file_kind(item["path"]) == "grid_v2" for item in group)
        if has_v2:
            for item in group:
                if _report_file_kind(item["path"]) == "grid":
                    dropped.append(item["path"])
                else:
                    kept.append(item)
        else:
            kept.extend(group)
    return kept, sorted(dropped)


def _production_completion(item):
    meta = item["meta"]
    completed = meta.get("completed_R")
    total = meta.get("R_total")
    try:
        completed_i = int(completed)
        total_i = int(total)
    except (TypeError, ValueError):
        return True, completed, total
    return completed_i >= total_i, completed_i, total_i


def _filter_incomplete_production(items, *, allow_partial=ALLOW_PARTIAL_PRODUCTION):
    kept = []
    excluded = []
    for item in items:
        complete, completed, total = _production_completion(item)
        if complete or allow_partial:
            kept.append(item)
        else:
            excluded.append({
                "path": item["path"],
                "completed_R": completed,
                "R_total": total,
                "dgp_type": item["meta"].get("dgp_type"),
                "N": item["meta"].get("N"),
                "T": item["meta"].get("Tp", item["meta"].get("T")),
                "select": item["meta"].get("select"),
            })
    return kept, excluded


def _grid_jsonl_paths():
    """Production simulation files only; excludes temp/smoke/check files."""
    paths = []
    for path in glob(os.path.join(SIM, "*.jsonl")):
        if _is_report_jsonl(path):
            paths.append(path)
    return sorted(paths)


def _load_grid_aggs(paths=None):
    global _LAST_DROPPED_DUPLICATE_JSONL, _LAST_EXCLUDED_INCOMPLETE_JSONL
    out = []
    missing = []
    for path in paths or _grid_jsonl_paths():
        try:
            agg = aggregate(path)
        except Exception as exc:  # keep one stale file from blocking all tables
            missing.append({"file": path, "reason": str(exc)})
            continue
        meta = dict(agg.get("_meta", {}))
        if not meta.get("Tp") or not meta.get("N"):
            m = re.search(r"grid[_-](\d+)", os.path.basename(path))
            if m:
                meta["Tp"] = int(m.group(1))
                meta["N"] = int(m.group(1))
        if meta.get("dgp_type") in (None, "", "unknown"):
            meta["dgp_type"] = "legacy"
        sidecar = path[:-len(".jsonl")] + ".meta.json" if path.endswith(".jsonl") else None
        if sidecar and os.path.exists(sidecar):
            try:
                with open(sidecar) as fh:
                    side_meta = json.load(fh)
                for key, val in side_meta.items():
                    current = meta.get(key)
                    missing_current = current is None
                    if isinstance(current, (float, np.floating)):
                        missing_current = missing_current or not np.isfinite(float(current))
                    if key not in meta or missing_current:
                        meta[key] = val
            except Exception:
                pass
        out.append({"path": path, "agg": agg, "meta": meta})
    out, excluded = _filter_incomplete_production(out)
    out, dropped = _resolve_duplicate_cells(out)
    _LAST_DROPPED_DUPLICATE_JSONL = dropped
    _LAST_EXCLUDED_INCOMPLETE_JSONL = excluded
    out.sort(key=lambda x: (
        str(x["meta"].get("dgp_type", "")),
        int(x["meta"].get("Tp", 0)),
        int(x["meta"].get("N", 0)),
        os.path.basename(x["path"]),
    ))
    return out, missing


def _metric(row, keys):
    for key in keys:
        if key in row and row[key] is not None:
            return row[key]
    return float("nan")


def _h_bandwidth(N):
    return int(math.floor(int(N) ** (1.0 / 3.0)))


def _main_inference(row, dgp):
    """Return table-ready inference metrics using theorem-aligned SEs."""
    if str(dgp).lower() in ("dgp2", "dgp3"):
        return {
            "se_type": "spatial-kernel",
            "mean_se": _metric(row, ["mean_se_spatial_kernel", "mean_se_spatial", "mean_se_xs"]),
            "size": _metric(row, ["size_5pct_spatial_kernel", "size_5pct_spatial", "size_5pct_xs"]),
            "coverage": _metric(row, ["coverage_95_spatial_kernel", "coverage_95_spatial", "coverage_95_xs", "cov_xs"]),
            "size_mcse": _metric(row, ["size_mcse_spatial_kernel", "size_mcse_spatial", "size_mcse_xs"]),
            "coverage_mcse": _metric(row, ["coverage_mcse_spatial_kernel", "coverage_mcse_spatial", "coverage_mcse_xs"]),
        }
    return {
        "se_type": "diagonal/white",
        "mean_se": _metric(row, ["mean_se_white", "mean_se"]),
        "size": _metric(row, ["size_5pct_white", "size_5pct"]),
        "coverage": _metric(row, ["coverage_95_white", "coverage_95", "cov"]),
        "size_mcse": _metric(row, ["size_mcse_white", "size_mcse"]),
        "coverage_mcse": _metric(row, ["coverage_mcse_white", "coverage_mcse"]),
    }


def main_performance_rows(items):
    rows = []
    missing = []
    for item in items:
        agg, meta = item["agg"], item["meta"]
        dgp = meta.get("dgp_type", "unknown")
        for target, vals in agg.items():
            if target.startswith("_"):
                continue
            inf = _main_inference(vals, dgp)
            row = {
                "DGP": _dgp_label(dgp),
                "target": _target_label(target),
                "T": meta.get("Tp", ""),
                "N": meta.get("N", ""),
                "true_value": _metric(vals, ["true_value", "mean_true_value"]),
                "mean_estimate": _metric(vals, ["mean_estimate"]),
                "bias": _metric(vals, ["bias"]),
                "rmse": _metric(vals, ["rmse"]),
                "se_type": inf["se_type"],
                "mean_se": inf["mean_se"],
                "empirical_size": inf["size"],
                "size_mcse": inf["size_mcse"],
                "coverage": inf["coverage"],
                "coverage_mcse": inf["coverage_mcse"],
                "replications": vals.get("R", ""),
            }
            for key in ("true_value", "mean_estimate", "bias", "rmse", "mean_se", "empirical_size", "coverage"):
                if not np.isfinite(float(row[key])) if row[key] != "" else True:
                    missing.append({"file": item["path"], "target": target, "field": key})
            rows.append(row)
    return rows, missing


def rank_frequency_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        rf = item["agg"].get("_rank_frequency", {})
        if not rf.get("available", False):
            continue
        if not rf.get("rank_selection_enabled", False):
            continue
        rows.append({
            "DGP": _dgp_label(rf.get("dgp_type", meta.get("dgp_type", "unknown"))),
            "T": rf.get("Tp", meta.get("Tp", "")),
            "N": rf.get("N", meta.get("N", "")),
            "J_min": rf.get("J_min", meta.get("J_min", "")),
            "kappa_c": rf.get("kappa_c", meta.get("kappa_c", "")),
            "retained_nonvalidation": meta.get("retained_nonvalidation", ""),
            "p_correct_rank": rf.get("p_correct_rank", ""),
            "p_underfit": rf.get("p_underfit", ""),
            "p_overfit": rf.get("p_overfit", ""),
            "modal_selected_rank": _rank_str(rf.get("modal_selected_rank")),
            "replications": rf.get("R", ""),
        })
    return rows


def fold_retention_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        q_T = meta.get("q_T", meta.get("q", ""))
        r_N = meta.get("r_N", meta.get("r", meta.get("buffer_r", "")))
        n_val = meta.get("N", "")
        rows.append({
            "DGP": _dgp_label(meta.get("dgp_type", "unknown")),
            "T": meta.get("Tp", ""),
            "N": n_val,
            "q_T": q_T,
            "r_N": r_N,
            "h_N": _h_bandwidth(n_val),
            "J_min": meta.get("J_min", ""),
            "realized_J": meta.get("J_realized", meta.get("J", "")),
            "retained_nonvalidation": meta.get("retained_nonvalidation", meta.get("retained", "")),
            "retained_total": meta.get("retained_total", ""),
        })
    return rows


def coeff_summary_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        rows.append({
            "DGP": _dgp_label(meta.get("dgp_type", "unknown")),
            "N": meta.get("N", ""),
            "T": meta.get("Tp", meta.get("T", "")),
            "mean(a_it)": meta.get("a_it_mean_mean", ""),
            "sd(a_it)": meta.get("a_it_sd_mean", ""),
            "min(a_it)": meta.get("a_it_min_min", ""),
            "max(a_it)": meta.get("a_it_max_max", ""),
            "max |a_it|": meta.get("max_abs_a_it_max", meta.get("max_abs_a_it_mean", "")),
            "mean(beta_it)": meta.get("beta_it_mean_mean", ""),
            "sd(beta_it)": meta.get("beta_it_sd_mean", ""),
            "min(beta_it)": meta.get("beta_it_min_min", ""),
            "max(beta_it)": meta.get("beta_it_max_max", ""),
            "mean PR2": meta.get("PR2_realized_mean", ""),
            "sd PR2": meta.get("PR2_realized_sd", ""),
            "c_xi": meta.get("c_xi", ""),
            "R": meta.get("completed_R", meta.get("R", "")),
        })
    return rows


def table_source_audit_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        rows.append({
            "table_source_file": os.path.basename(item["path"]),
            "dgp_type": meta.get("dgp_type", ""),
            "N": meta.get("N", ""),
            "T": meta.get("Tp", meta.get("T", "")),
            "R_total": meta.get("R_total", ""),
            "completed_R": meta.get("completed_R", meta.get("R", "")),
            "select": _as_bool(meta.get("select"), default=(_report_file_kind(item["path"]) == "rank")),
            "fixed_ranks": _rank_cell(meta.get("fixed_ranks", meta.get("selected_ranks_first_record"))),
            "mc_schema_version": meta.get("mc_schema_version", meta.get("_mc_schema_version", "")),
            "coefficient_summaries_available": _available(
                meta,
                "a_it_mean_mean",
                "a_it_sd_mean",
                "a_it_min_min",
                "a_it_max_max",
                "beta_it_mean_mean",
                "beta_it_sd_mean",
                "beta_it_min_min",
                "beta_it_max_max",
            ),
            "PR2_realized_available": _available(meta, "PR2_realized_mean", "PR2_realized_sd"),
            "profile_timing_available": _available(
                meta,
                "timing_mean_sec_per_rep",
                "timing_median_sec_per_rep",
                "timing_p90_sec_per_rep",
                "timing_mean_by_stage",
            ),
            "source_schema": _schema_source(item),
        })
    return rows


def _write_csv(path, rows, fields):
    def clean(val):
        if isinstance(val, (float, np.floating)) and not np.isfinite(float(val)):
            return ""
        return val

    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow({key: clean(row.get(key, "")) for key in fields})


def _remove_obsolete_tex():
    removed = []
    for folder in (OUT, PAPER_TABLES):
        if not os.path.isdir(folder):
            continue
        for name in OBSOLETE_OUTPUT_TEX:
            path = os.path.join(folder, name)
            if os.path.exists(path):
                os.remove(path)
                removed.append(path)
        if folder == PAPER_TABLES:
            for path in glob(os.path.join(folder, "*.tex")):
                name = os.path.basename(path)
                if (name.startswith("tab_mc_") or name in OBSOLETE_OUTPUT_TEX) and name not in ACTIVE_MANUSCRIPT_TEX:
                    os.remove(path)
                    removed.append(path)
    return removed


def _latex_table(rows, fields, align, caption_note=None):
    lines = [r"\begin{tabular}{" + align + "}", r"\toprule"]
    lines.append(" & ".join(_latex_escape(f) for f in fields) + r" \\")
    lines.append(r"\midrule")
    for row in rows:
        vals = []
        for fkey in fields:
            val = row.get(fkey, "")
            if val is None:
                vals.append("--")
            elif isinstance(val, (float, np.floating)):
                vals.append(fmt(val))
            else:
                vals.append(_latex_escape(val))
        lines.append(" & ".join(vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    if caption_note:
        lines.append("% " + caption_note)
    return "\n".join(lines)


def _write_tex(path, rows, fields, align, note=None):
    with open(path, "w") as fh:
        fh.write(_latex_table(rows, fields, align, note) + "\n")


def _write_fold_retention_tex(path, rows):
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\begin{threeparttable}",
        r"\caption{Fold counts and retained training shares for completed production cells.}",
        r"\label{tab:mc_folds}",
        r"\small",
        r"\setlength{\tabcolsep}{3.8pt}",
        r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l c c c c c c c S[table-format=1.3] S[table-format=1.3] @{}}",
        r"\toprule",
        (
            r"DGP & $N$ & $T$ & $q_T$ & $r_N$ & $h_N$ & $J_{\min}$ "
            r"& \makecell{Realized\\$J$} "
            r"& \multicolumn{1}{c}{\makecell{Retained\\non-val.}} "
            r"& \multicolumn{1}{c}{\makecell{Retained\\total}} \\"
        ),
        r"\midrule",
    ]
    for row in rows:
        lines.append(
            " & ".join([
                str(row["DGP"]),
                str(int(row["N"])),
                str(int(row["T"])),
                str(int(row["q_T"])),
                str(int(row["r_N"])),
                str(int(row["h_N"])),
                str(int(row["J_min"])),
                str(int(row["realized_J"])),
                fmt(row["retained_nonvalidation"], 3),
                fmt(row["retained_total"], 3),
            ]) + r" \\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular*}",
        r"\begin{tablenotes}[flushleft]",
        r"\footnotesize",
        r"\item \textit{Notes.} " + FOLD_RETENTION_TABLE_NOTE,
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _panel_rows_for_dgp(perf_rows, dgp_label, target_label):
    rows = [
        row for row in perf_rows
        if row.get("DGP") == dgp_label and row.get("target") == target_label
    ]
    return sorted(rows, key=lambda row: (int(row.get("N", 0)), int(row.get("T", 0))))


def _replication_note(rows):
    reps = sorted({int(row["replications"]) for row in rows if row.get("replications") not in ("", None)})
    if not reps:
        return "The number of replications is reported in the underlying diagnostic CSV."
    if reps == [1000]:
        return "The number of replications is 1000."
    parts = []
    for rep in reps:
        sizes = [
            f"$N=T={int(row['N'])}$"
            for row in rows
            if row.get("replications") not in ("", None) and int(row["replications"]) == rep
        ]
        parts.append(f"{rep} replications for {', '.join(sorted(set(sizes)))}")
    return "The number of replications is " + "; ".join(parts) + "."


def _dgp_note(dgp_label, displayed_rows):
    if dgp_label == "DGP 1":
        inference = "For DGP 1, inference uses the diagonal heteroskedasticity-robust standard error."
    else:
        inference = (
            "For DGPs 2--3, inference uses the Bartlett spatial-kernel standard error "
            "with lattice distance $d_N(i,j)=|i-j|$ and bandwidth "
            "$h_N=\\lfloor N^{1/3}\\rfloor$."
        )
    return (
        "Panel A reports the full mean of the autoregressive coefficient $a_{it}$, "
        "and Panel B reports the full mean of the slope coefficient $\\beta_{it}$. "
        "The full mean target averages over all units at the midpoint time "
        "$t^\\star=\\lfloor T/2\\rfloor+1$. "
        "Coefficient matrices and shocks are redrawn independently across replications. "
        "Bias and RMSE are computed from replication-level errors "
        "$\\widehat\\theta^{(r)}-\\theta_0^{(r)}$. "
        f"{inference} "
        "Size is the empirical rejection probability of the nominal two-sided 5\\% test. "
        "Coverage is empirical coverage of the nominal 95\\% confidence interval. "
        + _replication_note(displayed_rows)
    )


def _write_dgp_performance_tex(path, dgp_label, perf_rows):
    slug = dgp_label.lower().replace(" ", "")
    label = f"tab:mc_perf_{slug}"
    displayed = (
        _panel_rows_for_dgp(perf_rows, dgp_label, "lag full mean")
        + _panel_rows_for_dgp(perf_rows, dgp_label, "covariate full mean")
    )
    lines = [
        r"\begingroup",
        r"\small",
        r"\setlength{\LTleft}{0pt plus 1fill}",
        r"\setlength{\LTright}{0pt plus 1fill}",
        r"\begin{longtable}{ccrrrrrr}",
        (
            rf"\caption{{Monte Carlo fixed-rank inference performance: {dgp_label}.}}"
            rf"\label{{{label}}}"
            + (r"\label{tab:mc_main_summary}" if dgp_label == "DGP 1" else "")
            + r"\\"
        ),
        r"\toprule",
        r"$N$ & $T$ & true & bias & RMSE & mean s.e. & size & coverage \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"$N$ & $T$ & true & bias & RMSE & mean s.e. & size & coverage \\",
        r"\midrule",
        r"\endhead",
        r"\bottomrule",
        r"\endfoot",
        r"\multicolumn{8}{l}{\textit{Panel A. Autoregressive coefficient full mean}}\\",
    ]
    for row in _panel_rows_for_dgp(perf_rows, dgp_label, "lag full mean"):
        lines.append(
            " & ".join([
                str(int(row["N"])),
                str(int(row["T"])),
                fmt(row["true_value"], 3),
                fmt(row["bias"], 3),
                fmt(row["rmse"], 3),
                fmt(row["mean_se"], 3),
                fmt(row["empirical_size"], 3),
                fmt(row["coverage"], 3),
            ]) + r" \\"
        )
    lines += [
        r"\addlinespace",
        r"\multicolumn{8}{l}{\textit{Panel B. Slope coefficient full mean}}\\",
    ]
    for row in _panel_rows_for_dgp(perf_rows, dgp_label, "covariate full mean"):
        lines.append(
            " & ".join([
                str(int(row["N"])),
                str(int(row["T"])),
                fmt(row["true_value"], 3),
                fmt(row["bias"], 3),
                fmt(row["rmse"], 3),
                fmt(row["mean_se"], 3),
                fmt(row["empirical_size"], 3),
                fmt(row["coverage"], 3),
            ]) + r" \\"
        )
    lines += [
        r"\end{longtable}",
        r"\par\smallskip",
        r"{\footnotesize\begin{minipage}{0.92\textwidth}\textit{Notes:} "
        + _dgp_note(dgp_label, displayed)
        + r"\end{minipage}}",
        r"\endgroup",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_main_summary_tex(path, *, prefix="tables"):
    lines = [
        rf"\input{{{prefix}/tab_mc_perf_dgp1.tex}}",
        rf"\input{{{prefix}/tab_mc_perf_dgp2.tex}}",
        rf"\input{{{prefix}/tab_mc_perf_dgp3.tex}}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_table_alias(path, source, *, caption, label, note=None):
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering\small",
        rf"\caption{{{caption}}}",
        rf"\label{{{label}}}",
        r"\resizebox{\textwidth}{!}{%",
        rf"\input{{{source}}}%",
        r"}",
    ]
    if note:
        lines += [
            r"\par\smallskip",
            r"{\footnotesize\begin{minipage}{0.92\textwidth}\textit{Notes:} "
            + note
            + r"\end{minipage}}",
        ]
    lines.append(r"\end{table}")
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_rank_table(path, rows):
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering\small",
        r"\caption{Monte Carlo rank-selection accuracy.}",
        r"\label{tab:mc_rank}",
        r"\begin{tabular}{lrrrrrrrrlr}",
        r"\toprule",
        r"DGP & $T$ & $N$ & $J_{\min}$ & $c_\kappa$ & retained non-val. & $P(\mathrm{correct})$ & $P(\mathrm{under})$ & $P(\mathrm{over})$ & modal rank & reps \\",
        r"\midrule",
    ]
    if rows:
        for row in rows:
            lines.append(
                " & ".join([
                    str(row.get("DGP", "")),
                    str(int(row["T"])) if row.get("T") not in ("", None) else "--",
                    str(int(row["N"])) if row.get("N") not in ("", None) else "--",
                    str(int(row["J_min"])) if row.get("J_min") not in ("", None) else "--",
                    fmt(row.get("kappa_c"), 3),
                    fmt(row.get("retained_nonvalidation"), 3),
                    fmt(row.get("p_correct_rank"), 3),
                    fmt(row.get("p_underfit"), 3),
                    fmt(row.get("p_overfit"), 3),
                    str(row.get("modal_selected_rank", "--")),
                    str(int(row["replications"])) if row.get("replications") not in ("", None) else "--",
                ]) + r" \\"
            )
    else:
        lines.append(r"\multicolumn{11}{c}{No rank-selection production runs are currently available.}\\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}",
        r"\par\smallskip",
        r"{\footnotesize\begin{minipage}{0.92\textwidth}\textit{Notes:} "
        r"The table is populated only by production rank-selection runs. Fixed-rank "
        r"performance runs are omitted, so the placeholder row remains until "
        r"\texttt{rank\_*.jsonl} "
        r"production files are completed."
        r"\end{minipage}}",
        r"\end{table}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_coeff_summary_tex(path, rows):
    fields = [
        "DGP", "N", "T", "mean(a_it)", "sd(a_it)", "min(a_it)", "max(a_it)",
        "max |a_it|", "mean(beta_it)", "sd(beta_it)", "min(beta_it)",
        "max(beta_it)", "mean PR2", "sd PR2", "c_xi", "R",
    ]
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering\small",
        r"\caption{Monte Carlo coefficient and signal summaries.}",
        r"\label{tab:mc_coeff_summary}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lrrrrrrrrrrrrrrr}",
        r"\toprule",
        r"DGP & $N$ & $T$ & mean $a_{it}$ & sd $a_{it}$ & min $a_{it}$ & max $a_{it}$ & max $|a_{it}|$ & mean $\beta_{it}$ & sd $\beta_{it}$ & min $\beta_{it}$ & max $\beta_{it}$ & mean PR$^2$ & sd PR$^2$ & $c_\xi$ & reps \\",
        r"\midrule",
    ]
    for row in rows:
        vals = []
        for field in fields:
            val = row.get(field, "")
            if field in {"DGP"}:
                vals.append(str(val))
            elif field in {"N", "T", "R"} and val not in ("", None):
                vals.append(str(int(val)))
            else:
                vals.append(fmt(val, 3))
        lines.append(" & ".join(vals) + r" \\")
    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\par\smallskip",
        r"{\footnotesize\begin{minipage}{0.92\textwidth}\textit{Notes:} "
        r"Coefficient and signal summaries are computed over Monte Carlo replications "
        r"when the JSONL records contain DGP diagnostics. Older completed runs that "
        r"predate these per-replication diagnostics display ``--'' for unavailable "
        r"quantities."
        r"\end{minipage}}",
        r"\end{table}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _write_opt_table(path, items):
    rows = []
    for item in items:
        meta = item["meta"]
        rows.append({
            "DGP": _dgp_label(meta.get("dgp_type", "unknown")),
            "N": meta.get("N", ""),
            "T": meta.get("Tp", meta.get("T", "")),
            "mean_sweeps": meta.get("optimization_mean_sweeps", ""),
            "restart_improve": meta.get("optimization_frac_restart_improve_gt_1e_6", ""),
            "monotone": meta.get("optimization_monotone_rate", meta.get("monotone_rate", "")),
            "sweep_cap": meta.get("optimization_sweep_cap_hit_rate", ""),
            "small_decrease": meta.get("optimization_frac_final_decrease_lt_1e_6", ""),
            "total_sec": meta.get("timing_mean_sec_per_rep", ""),
            "first_stage_sec": meta.get("timing_mean_by_stage", {}).get("_time_first_stage_sec", "")
            if isinstance(meta.get("timing_mean_by_stage"), dict) else "",
            "riesz_sec": meta.get("timing_mean_by_stage", {}).get("_time_riesz_sec", "")
            if isinstance(meta.get("timing_mean_by_stage"), dict) else "",
        })
    rows = sorted(rows, key=lambda row: (row["DGP"], int(row["N"] or 0), int(row["T"] or 0)))
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering\small",
        r"\caption{Monte Carlo optimization diagnostics.}",
        r"\label{tab:mc_opt}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lrrrrrrrrrr}",
        r"\toprule",
        r"DGP & $N$ & $T$ & mean sweeps & sweep-cap hit rate & monotone rate & final decrease $<10^{-6}$ & restart improvement $>10^{-6}$ & mean total sec. & mean first-stage sec. & mean Riesz sec. \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(
            " & ".join([
                str(row["DGP"]),
                str(int(row["N"])) if row["N"] != "" else "--",
                str(int(row["T"])) if row["T"] != "" else "--",
                fmt(row["mean_sweeps"], 3),
                fmt(row["sweep_cap"], 3),
                fmt(row["monotone"], 3),
                fmt(row["small_decrease"], 3),
                fmt(row["restart_improve"], 3),
                fmt(row["total_sec"], 3),
                fmt(row["first_stage_sec"], 3),
                fmt(row["riesz_sec"], 3),
            ]) + r" \\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\par\smallskip",
        r"{\footnotesize\begin{minipage}{0.92\textwidth}\textit{Notes:} "
        r"Optimization diagnostics are numerical implementation diagnostics for the "
        r"nonconvex first-stage problem. A sweep-cap hit is treated as a resource-use "
        r"diagnostic rather than an automatic estimator failure, especially when the "
        r"final relative objective decrease is small."
        r"\end{minipage}}",
        r"\end{table}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _copy_text(src, dst):
    with open(src) as fh:
        text = fh.read()
    with open(dst, "w") as fh:
        fh.write(text)


def _copy_text_replace(src, dst, replacements):
    with open(src) as fh:
        text = fh.read()
    for old, new in replacements:
        text = text.replace(old, new)
    with open(dst, "w") as fh:
        fh.write(text)


def _write_manuscript_tables(items, perf):
    os.makedirs(PAPER_TABLES, exist_ok=True)
    for dgp in ("DGP 1", "DGP 2", "DGP 3"):
        name = f"tab_mc_perf_dgp{dgp[-1]}.tex"
        _write_dgp_performance_tex(os.path.join(OUT, name), dgp, perf)
        _write_dgp_performance_tex(os.path.join(PAPER_TABLES, name), dgp, perf)
    _write_main_summary_tex(os.path.join(OUT, "tab_mc_main_summary.tex"), prefix="outputs/sim/tables")
    _write_main_summary_tex(os.path.join(PAPER_TABLES, "tab_mc_main_summary.tex"), prefix="tables")
    # These are written by write_journal_tables into OUT first, then mirrored below.
    for name in ("tab_mc_rank.tex", "tab_mc_coeff_summary.tex", "tab_mc_folds.tex", "tab_mc_opt.tex"):
        _copy_text(os.path.join(OUT, name), os.path.join(PAPER_TABLES, name))


def _render_performance_rows(rows, *, include_size: bool):
    out = []
    for row in rows:
        rendered = {
            "DGP": row.get("DGP", ""),
            "target": _paper_target_label(row.get("target", "")),
            "N": row.get("N", ""),
            "T": row.get("T", ""),
            "true": row.get("true_value", ""),
            "mean estimate": row.get("mean_estimate", ""),
            "bias": row.get("bias", ""),
            "RMSE": row.get("rmse", ""),
            "mean s.e.": row.get("mean_se", ""),
            "coverage": row.get("coverage", ""),
            "R": row.get("replications", ""),
        }
        if include_size:
            rendered = {
                "DGP": rendered["DGP"],
                "target": rendered["target"],
                "N": rendered["N"],
                "T": rendered["T"],
                "true": rendered["true"],
                "mean estimate": rendered["mean estimate"],
                "bias": rendered["bias"],
                "RMSE": rendered["RMSE"],
                "mean s.e.": rendered["mean s.e."],
                "size": row.get("empirical_size", ""),
                "coverage": rendered["coverage"],
                "R": rendered["R"],
            }
        out.append(rendered)
    return out


def write_journal_tables(items):
    os.makedirs(OUT, exist_ok=True)
    perf, missing = main_performance_rows(items)
    rank = rank_frequency_rows(items)
    folds = fold_retention_rows(items)
    coeff = coeff_summary_rows(items)
    source_audit = table_source_audit_rows(items)

    perf_fields = [
        "DGP", "target", "T", "N", "true_value", "mean_estimate", "bias", "rmse",
        "se_type", "mean_se", "empirical_size", "size_mcse", "coverage",
        "coverage_mcse", "replications",
    ]
    rank_fields = [
        "DGP", "T", "N", "J_min", "kappa_c", "retained_nonvalidation",
        "p_correct_rank", "p_underfit", "p_overfit", "modal_selected_rank",
        "replications",
    ]
    fold_fields = [
        "DGP", "N", "T", "q_T", "r_N", "h_N", "J_min", "realized_J",
        "retained_nonvalidation", "retained_total",
    ]
    coeff_fields = [
        "DGP", "N", "T", "mean(a_it)", "sd(a_it)", "min(a_it)", "max(a_it)",
        "max |a_it|", "mean(beta_it)", "sd(beta_it)", "min(beta_it)",
        "max(beta_it)", "mean PR2", "sd PR2", "c_xi", "R",
    ]
    audit_fields = [
        "table_source_file", "dgp_type", "N", "T", "R_total", "completed_R",
        "select", "fixed_ranks", "mc_schema_version",
        "coefficient_summaries_available", "PR2_realized_available",
        "profile_timing_available", "source_schema",
    ]

    _write_csv(os.path.join(OUT, "tab_mc_performance.csv"), perf, perf_fields)
    _write_csv(os.path.join(OUT, "tab_rank_frequency.csv"), rank, rank_fields)
    _write_csv(os.path.join(OUT, "tab_fold_retention.csv"), folds, fold_fields)
    _write_csv(os.path.join(OUT, "tab_mc_coeff_summary.csv"), coeff, coeff_fields)
    _write_csv(os.path.join(OUT, "table_source_audit.csv"), source_audit, audit_fields)

    _write_rank_table(os.path.join(OUT, "tab_mc_rank.tex"), rank)
    _write_coeff_summary_tex(os.path.join(OUT, "tab_mc_coeff_summary.tex"), coeff)
    _write_fold_retention_tex(os.path.join(OUT, "tab_mc_folds.tex"), folds)
    _write_opt_table(os.path.join(OUT, "tab_mc_opt.tex"), items)
    _write_manuscript_tables(items, perf)
    removed = _remove_obsolete_tex()
    return {"performance": perf, "rank": rank, "folds": folds, "coeff": coeff,
            "source_audit": source_audit, "missing": missing, "removed_obsolete_tex": removed}


def main():
    items, load_missing = _load_grid_aggs()
    if not items:
        print("no grid*.jsonl files found in outputs/sim/")
        return
    result = write_journal_tables(items)
    for name in (
        "tab_mc_performance.csv",
        "tab_mc_main_summary.tex",
        "tab_mc_perf_dgp1.tex",
        "tab_mc_perf_dgp2.tex",
        "tab_mc_perf_dgp3.tex",
        "tab_rank_frequency.csv",
        "tab_mc_coeff_summary.csv",
        "table_source_audit.csv",
        "tab_mc_coeff_summary.tex",
        "tab_fold_retention.csv",
        "tab_mc_folds.tex",
        "tab_mc_rank.tex",
        "tab_mc_opt.tex",
    ):
        print(f"wrote {os.path.join(OUT, name)}")
    if result["removed_obsolete_tex"]:
        print(f"removed {len(result['removed_obsolete_tex'])} obsolete table tex file(s):")
        for path in result["removed_obsolete_tex"]:
            print("  " + os.path.relpath(path, ROOT))
    if load_missing:
        print(f"skipped {len(load_missing)} unreadable grid file(s)")
    if _LAST_EXCLUDED_INCOMPLETE_JSONL:
        print(f"excluded {len(_LAST_EXCLUDED_INCOMPLETE_JSONL)} incomplete production file(s):")
        for item in _LAST_EXCLUDED_INCOMPLETE_JSONL:
            print(
                "  "
                + os.path.basename(item["path"])
                + f" completed_R={item['completed_R']} R_total={item['R_total']}"
            )
    if _LAST_DROPPED_DUPLICATE_JSONL:
        print(f"dropped {len(_LAST_DROPPED_DUPLICATE_JSONL)} older duplicate file(s):")
        for path in _LAST_DROPPED_DUPLICATE_JSONL:
            print("  " + os.path.basename(path))
    print("included production files:")
    for item in items:
        meta = item["meta"]
        print(
            "  "
            + os.path.basename(item["path"])
            + f" [{_schema_source(item)}]"
            + f" dgp_type={meta.get('dgp_type', '')}"
            + f" N={meta.get('N', '')}"
            + f" T={meta.get('Tp', meta.get('T', ''))}"
            + f" completed_R={meta.get('completed_R', '')}"
            + f" R_total={meta.get('R_total', '')}"
        )
    old_schema = [row for row in result["source_audit"] if row["source_schema"] == "old grid"]
    v2_schema = [row for row in result["source_audit"] if row["source_schema"] == "grid_v2"]
    print("old-schema rows still used:")
    for row in old_schema:
        print(
            "  "
            + row["table_source_file"]
            + f" dgp_type={row['dgp_type']} N={row['N']} T={row['T']}"
        )
    print("grid_v2 rows used:")
    for row in v2_schema:
        print(
            "  "
            + row["table_source_file"]
            + f" dgp_type={row['dgp_type']} N={row['N']} T={row['T']}"
        )
    if result["missing"]:
        print(f"missing numeric fields in {len(result['missing'])} table cell(s); see old-schema inputs")
    print(f"grid aggregates reported: {len(items)}")


if __name__ == "__main__":
    main()
