#!/usr/bin/env python3
"""Build journal-ready Monte Carlo tables from ``outputs/sim/*.jsonl``.

The revised MC schema stores truth, estimates, White/diagonal inference,
spatial-kernel inference, rank-selection metadata, and fold-retention diagnostics.
This script re-aggregates JSONL checkpoints with :func:`dlrhcs.mc.aggregate` and
writes CSV plus LaTeX fragments to ``outputs/sim/tables/``.
"""
from __future__ import annotations

import csv
import json
import math
import os
import re
import sys
from glob import glob

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from dlrhcs.mc import aggregate  # noqa: E402

SIM = os.path.join(ROOT, "outputs", "sim")
OUT = os.path.join(SIM, "tables")

TARGET_OBJECT = {"lag": "lag", "slope": "covariate"}
TARGET_TYPE = {
    "entry": "entry",
    "gmean": "group mean",
    "fmean": "full mean",
    "contrast": "contrast",
}

PAPER_TARGET_LABELS = {
    "lag entry": "AR entry",
    "lag group mean": "AR group mean",
    "lag full mean": "AR full mean",
    "lag contrast": "AR group contrast",
    "covariate entry": "Slope entry",
    "covariate group mean": "Slope group mean",
    "covariate full mean": "Slope full mean",
    "covariate contrast": "Slope group contrast",
}

PERFORMANCE_TABLE_NOTE = (
    "DGP 1 reports diagonal/White inference. DGP 2--3 report spatial-kernel "
    "inference with a Bartlett kernel on the lattice distance |i-j| and "
    "bandwidth h_N=floor(N^(1/3)). Entry targets use "
    "i*=floor(N/2)+1 and t*=floor(T/2)+1. Group 1 is the first half of units, "
    "Group 0 is the second half, and contrasts are Group 1 mean minus Group 0 mean."
)

MAIN_PERFORMANCE_TABLE_NOTE = (
    "Coverage is the empirical frequency with which the nominal 95 percent "
    "confidence interval contains the true target value. DGP 1 reports "
    "diagonal/White inference. DGP 2--3 report spatial-kernel inference with a "
    "Bartlett kernel on the lattice distance |i-j| and bandwidth "
    "h_N=floor(N^(1/3)). Entry targets use i*=floor(N/2)+1 and "
    "t*=floor(T/2)+1. Group 1 is the first half of units, Group 0 is the "
    "second half, and contrasts are Group 1 mean minus Group 0 mean."
)

FULL_PERFORMANCE_TABLE_NOTE = (
    "Size is the empirical rejection frequency for the nominal 5 percent "
    "two-sided test, and coverage is the empirical frequency with which the "
    "nominal 95 percent confidence interval contains the true target value. "
    "DGP 1 reports diagonal/White inference. DGP 2--3 report spatial-kernel "
    "inference with a Bartlett kernel on the lattice distance |i-j| and "
    "bandwidth h_N=floor(N^(1/3))."
)

FOLD_RETENTION_TABLE_NOTE = (
    "This table reports cross-fitting quantities only. The spatial-kernel "
    "bandwidth $h_N$ does not affect the retained training shares. For DGPs "
    "2--3, inference uses Bartlett spatial-kernel standard errors with "
    "$h_N=\\lfloor N^{1/3}\\rfloor$. The quantity $q_T$ is the time buffer "
    "used in cross-fitting, and $r_N$ is the unit or spatial buffer. The "
    "quantity $J$ is the realized number of folds generated by the finite-fold "
    "rule unless manually overridden. ``Retained non-validation'' is the "
    "average share of non-validation cells remaining after buffer deletion. "
    "``Retained total'' is the average number of retained training cells "
    "divided by the total number of cells, $NT$. The retained shares are "
    "averaged over the realized scattered-fold assignments and production "
    "replications. Consequently, small differences across runs or master seeds "
    "are expected before rounding."
)


def fmt(x, d=3):
    """Format numbers without leading plus signs; return -- for missing values."""
    if x is None:
        return "--"
    try:
        xx = float(x)
    except (TypeError, ValueError):
        return str(x)
    if not np.isfinite(xx):
        return "--"
    return f"{xx:.{d}f}"


def _latex_escape(x):
    return str(x).replace("_", r"\_")


def _rank_str(rank):
    if rank is None:
        return "--"
    return "(" + ",".join(str(int(x)) for x in rank) + ")"


def _dgp_label(dgp):
    key = str(dgp or "unknown").lower()
    labels = {"dgp1": "DGP 1", "dgp2": "DGP 2", "dgp3": "DGP 3", "legacy": "legacy"}
    return labels.get(key, str(dgp or "unknown"))


def _target_label(name):
    if "_" not in name:
        return name
    obj, kind = name.split("_", 1)
    return f"{TARGET_OBJECT.get(obj, obj)} {TARGET_TYPE.get(kind, kind)}"


def _paper_target_label(label):
    return PAPER_TARGET_LABELS.get(str(label), str(label))


EXCLUDED_JSONL_PREFIXES = ("tmp_", "smoke_", "test_")
REPORT_JSONL_PREFIXES = ("grid_", "grid_v2_", "rank_")
_LAST_DROPPED_DUPLICATE_JSONL = []


def _is_report_jsonl(path):
    base = os.path.basename(path)
    if base.startswith(EXCLUDED_JSONL_PREFIXES):
        return False
    return base.startswith(REPORT_JSONL_PREFIXES)


def _report_file_kind(path):
    base = os.path.basename(path)
    if base.startswith("grid_v2_"):
        return "grid_v2"
    if base.startswith("grid_"):
        return "grid"
    if base.startswith("rank_"):
        return "rank"
    return "other"


def _as_bool(value, default=False):
    if value is None:
        return bool(default)
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, np.integer)):
        return bool(value)
    text = str(value).strip().lower()
    if text in {"1", "true", "t", "yes", "y"}:
        return True
    if text in {"0", "false", "f", "no", "n"}:
        return False
    return bool(default)


def _rank_tuple(value):
    if value in (None, ""):
        return None
    if isinstance(value, str):
        parts = [part.strip() for part in value.replace("(", "").replace(")", "").split(",")]
        try:
            return tuple(int(part) for part in parts if part != "")
        except ValueError:
            return (value,)
    try:
        return tuple(int(part) for part in value)
    except TypeError:
        try:
            return (int(value),)
        except (TypeError, ValueError):
            return (str(value),)


def _int_meta(meta, *keys):
    for key in keys:
        value = meta.get(key)
        if value not in (None, ""):
            return int(value)
    return None


def _duplicate_cell_key(item):
    meta = item["meta"]
    kind = _report_file_kind(item["path"])
    select = _as_bool(meta.get("select"), default=(kind == "rank"))
    if select:
        mode = (
            "rank-selection",
            _rank_tuple(meta.get("true_ranks", meta.get("true_ranks_from_records"))),
            _rank_tuple(meta.get("rank_caps")),
        )
    else:
        mode = (
            "fixed-rank",
            _rank_tuple(meta.get("fixed_ranks", meta.get("selected_ranks_first_record"))),
        )
    return (
        str(meta.get("dgp_type", "")).lower(),
        _int_meta(meta, "N"),
        _int_meta(meta, "Tp", "T"),
        bool(select),
        mode,
    )


def _resolve_duplicate_cells(items):
    """Prefer grid_v2 over grid for the same fixed-rank production cell."""
    grouped = {}
    passthrough = []
    for item in items:
        kind = _report_file_kind(item["path"])
        select = _as_bool(item["meta"].get("select"), default=(kind == "rank"))
        if kind in {"grid", "grid_v2"} and not select:
            grouped.setdefault(_duplicate_cell_key(item), []).append(item)
        else:
            passthrough.append(item)

    kept = list(passthrough)
    dropped = []
    for group in grouped.values():
        has_v2 = any(_report_file_kind(item["path"]) == "grid_v2" for item in group)
        if has_v2:
            for item in group:
                if _report_file_kind(item["path"]) == "grid":
                    dropped.append(item["path"])
                else:
                    kept.append(item)
        else:
            kept.extend(group)
    return kept, sorted(dropped)


def _grid_jsonl_paths():
    """Production simulation files only; excludes temp/smoke/check files."""
    paths = []
    for path in glob(os.path.join(SIM, "*.jsonl")):
        if _is_report_jsonl(path):
            paths.append(path)
    return sorted(paths)


def _load_grid_aggs(paths=None):
    global _LAST_DROPPED_DUPLICATE_JSONL
    out = []
    missing = []
    for path in paths or _grid_jsonl_paths():
        try:
            agg = aggregate(path)
        except Exception as exc:  # keep one stale file from blocking all tables
            missing.append({"file": path, "reason": str(exc)})
            continue
        meta = dict(agg.get("_meta", {}))
        if not meta.get("Tp") or not meta.get("N"):
            m = re.search(r"grid[_-](\d+)", os.path.basename(path))
            if m:
                meta["Tp"] = int(m.group(1))
                meta["N"] = int(m.group(1))
        if meta.get("dgp_type") in (None, "", "unknown"):
            meta["dgp_type"] = "legacy"
        sidecar = path[:-len(".jsonl")] + ".meta.json" if path.endswith(".jsonl") else None
        if sidecar and os.path.exists(sidecar):
            try:
                with open(sidecar) as fh:
                    side_meta = json.load(fh)
                for key, val in side_meta.items():
                    current = meta.get(key)
                    missing_current = current is None
                    if isinstance(current, (float, np.floating)):
                        missing_current = missing_current or not np.isfinite(float(current))
                    if key not in meta or missing_current:
                        meta[key] = val
            except Exception:
                pass
        out.append({"path": path, "agg": agg, "meta": meta})
    out, dropped = _resolve_duplicate_cells(out)
    _LAST_DROPPED_DUPLICATE_JSONL = dropped
    out.sort(key=lambda x: (
        str(x["meta"].get("dgp_type", "")),
        int(x["meta"].get("Tp", 0)),
        int(x["meta"].get("N", 0)),
        os.path.basename(x["path"]),
    ))
    return out, missing


def _metric(row, keys):
    for key in keys:
        if key in row and row[key] is not None:
            return row[key]
    return float("nan")


def _h_bandwidth(N):
    return int(math.floor(int(N) ** (1.0 / 3.0)))


def _main_inference(row, dgp):
    """Return table-ready inference metrics using theorem-aligned SEs."""
    if str(dgp).lower() in ("dgp2", "dgp3"):
        return {
            "se_type": "spatial-kernel",
            "mean_se": _metric(row, ["mean_se_spatial_kernel", "mean_se_spatial", "mean_se_xs"]),
            "size": _metric(row, ["size_5pct_spatial_kernel", "size_5pct_spatial", "size_5pct_xs"]),
            "coverage": _metric(row, ["coverage_95_spatial_kernel", "coverage_95_spatial", "coverage_95_xs", "cov_xs"]),
            "size_mcse": _metric(row, ["size_mcse_spatial_kernel", "size_mcse_spatial", "size_mcse_xs"]),
            "coverage_mcse": _metric(row, ["coverage_mcse_spatial_kernel", "coverage_mcse_spatial", "coverage_mcse_xs"]),
        }
    return {
        "se_type": "diagonal/white",
        "mean_se": _metric(row, ["mean_se_white", "mean_se"]),
        "size": _metric(row, ["size_5pct_white", "size_5pct"]),
        "coverage": _metric(row, ["coverage_95_white", "coverage_95", "cov"]),
        "size_mcse": _metric(row, ["size_mcse_white", "size_mcse"]),
        "coverage_mcse": _metric(row, ["coverage_mcse_white", "coverage_mcse"]),
    }


def main_performance_rows(items):
    rows = []
    missing = []
    for item in items:
        agg, meta = item["agg"], item["meta"]
        dgp = meta.get("dgp_type", "unknown")
        for target, vals in agg.items():
            if target.startswith("_"):
                continue
            inf = _main_inference(vals, dgp)
            row = {
                "DGP": _dgp_label(dgp),
                "target": _target_label(target),
                "T": meta.get("Tp", ""),
                "N": meta.get("N", ""),
                "true_value": _metric(vals, ["true_value", "mean_true_value"]),
                "mean_estimate": _metric(vals, ["mean_estimate"]),
                "bias": _metric(vals, ["bias"]),
                "rmse": _metric(vals, ["rmse"]),
                "se_type": inf["se_type"],
                "mean_se": inf["mean_se"],
                "empirical_size": inf["size"],
                "size_mcse": inf["size_mcse"],
                "coverage": inf["coverage"],
                "coverage_mcse": inf["coverage_mcse"],
                "replications": vals.get("R", ""),
            }
            for key in ("true_value", "mean_estimate", "bias", "rmse", "mean_se", "empirical_size", "coverage"):
                if not np.isfinite(float(row[key])) if row[key] != "" else True:
                    missing.append({"file": item["path"], "target": target, "field": key})
            rows.append(row)
    return rows, missing


def rank_frequency_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        rf = item["agg"].get("_rank_frequency", {})
        if not rf.get("available", False):
            continue
        if not rf.get("rank_selection_enabled", False):
            continue
        rows.append({
            "DGP": _dgp_label(rf.get("dgp_type", meta.get("dgp_type", "unknown"))),
            "T": rf.get("Tp", meta.get("Tp", "")),
            "N": rf.get("N", meta.get("N", "")),
            "J_min": rf.get("J_min", meta.get("J_min", "")),
            "kappa_c": rf.get("kappa_c", meta.get("kappa_c", "")),
            "retained_nonvalidation": meta.get("retained_nonvalidation", ""),
            "p_correct_rank": rf.get("p_correct_rank", ""),
            "p_underfit": rf.get("p_underfit", ""),
            "p_overfit": rf.get("p_overfit", ""),
            "modal_selected_rank": _rank_str(rf.get("modal_selected_rank")),
            "replications": rf.get("R", ""),
        })
    return rows


def fold_retention_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        q_T = meta.get("q_T", meta.get("q", ""))
        r_N = meta.get("r_N", meta.get("r", meta.get("buffer_r", "")))
        n_val = meta.get("N", "")
        rows.append({
            "DGP": _dgp_label(meta.get("dgp_type", "unknown")),
            "T": meta.get("Tp", ""),
            "N": n_val,
            "q_T": q_T,
            "r_N": r_N,
            "h_N": _h_bandwidth(n_val),
            "J_min": meta.get("J_min", ""),
            "realized_J": meta.get("J_realized", meta.get("J", "")),
            "retained_nonvalidation": meta.get("retained_nonvalidation", meta.get("retained", "")),
            "retained_total": meta.get("retained_total", ""),
        })
    return rows


def coeff_summary_rows(items):
    rows = []
    for item in items:
        meta = item["meta"]
        rows.append({
            "DGP": _dgp_label(meta.get("dgp_type", "unknown")),
            "N": meta.get("N", ""),
            "T": meta.get("Tp", meta.get("T", "")),
            "mean(a_it)": meta.get("a_it_mean_mean", ""),
            "sd(a_it)": meta.get("a_it_sd_mean", ""),
            "min(a_it)": meta.get("a_it_min_min", ""),
            "max(a_it)": meta.get("a_it_max_max", ""),
            "max |a_it|": meta.get("max_abs_a_it_max", meta.get("max_abs_a_it_mean", "")),
            "mean(beta_it)": meta.get("beta_it_mean_mean", ""),
            "sd(beta_it)": meta.get("beta_it_sd_mean", ""),
            "min(beta_it)": meta.get("beta_it_min_min", ""),
            "max(beta_it)": meta.get("beta_it_max_max", ""),
            "mean PR2": meta.get("PR2_realized_mean", ""),
            "sd PR2": meta.get("PR2_realized_sd", ""),
            "c_xi": meta.get("c_xi", ""),
            "R": meta.get("completed_R", meta.get("R", "")),
        })
    return rows


def _write_csv(path, rows, fields):
    def clean(val):
        if isinstance(val, (float, np.floating)) and not np.isfinite(float(val)):
            return ""
        return val

    with open(path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow({key: clean(row.get(key, "")) for key in fields})


def _latex_table(rows, fields, align, caption_note=None):
    lines = [r"\begin{tabular}{" + align + "}", r"\toprule"]
    lines.append(" & ".join(_latex_escape(f) for f in fields) + r" \\")
    lines.append(r"\midrule")
    for row in rows:
        vals = []
        for fkey in fields:
            val = row.get(fkey, "")
            if val is None:
                vals.append("--")
            elif isinstance(val, (float, np.floating)):
                vals.append(fmt(val))
            else:
                vals.append(_latex_escape(val))
        lines.append(" & ".join(vals) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    if caption_note:
        lines.append("% " + caption_note)
    return "\n".join(lines)


def _write_tex(path, rows, fields, align, note=None):
    with open(path, "w") as fh:
        fh.write(_latex_table(rows, fields, align, note) + "\n")


def _write_fold_retention_tex(path, rows):
    lines = [
        r"\begin{table}[!htbp]",
        r"\centering",
        r"\begin{threeparttable}",
        r"\caption{Fold counts and retained training shares for completed production cells.}",
        r"\label{tab:fold-counts}",
        r"\small",
        r"\setlength{\tabcolsep}{3.8pt}",
        r"\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}} l c c c c c c c S[table-format=1.3] S[table-format=1.3] @{}}",
        r"\toprule",
        (
            r"DGP & $N$ & $T$ & $q_T$ & $r_N$ & $h_N$ & $J_{\min}$ "
            r"& \makecell{Realized\\$J$} "
            r"& \multicolumn{1}{c}{\makecell{Retained\\non-validation}} "
            r"& \multicolumn{1}{c}{\makecell{Retained\\total}} \\"
        ),
        r"\midrule",
    ]
    for row in rows:
        lines.append(
            " & ".join([
                str(row["DGP"]),
                str(int(row["N"])),
                str(int(row["T"])),
                str(int(row["q_T"])),
                str(int(row["r_N"])),
                str(int(row["h_N"])),
                str(int(row["J_min"])),
                str(int(row["realized_J"])),
                fmt(row["retained_nonvalidation"], 3),
                fmt(row["retained_total"], 3),
            ]) + r" \\"
        )
    lines += [
        r"\bottomrule",
        r"\end{tabular*}",
        r"\begin{tablenotes}[flushleft]",
        r"\footnotesize",
        r"\item \textit{Notes.} " + FOLD_RETENTION_TABLE_NOTE,
        r"\end{tablenotes}",
        r"\end{threeparttable}",
        r"\end{table}",
    ]
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")


def _render_performance_rows(rows, *, include_size: bool):
    out = []
    for row in rows:
        rendered = {
            "DGP": row.get("DGP", ""),
            "target": _paper_target_label(row.get("target", "")),
            "N": row.get("N", ""),
            "T": row.get("T", ""),
            "true": row.get("true_value", ""),
            "mean estimate": row.get("mean_estimate", ""),
            "bias": row.get("bias", ""),
            "RMSE": row.get("rmse", ""),
            "mean s.e.": row.get("mean_se", ""),
            "coverage": row.get("coverage", ""),
            "R": row.get("replications", ""),
        }
        if include_size:
            rendered = {
                "DGP": rendered["DGP"],
                "target": rendered["target"],
                "N": rendered["N"],
                "T": rendered["T"],
                "true": rendered["true"],
                "mean estimate": rendered["mean estimate"],
                "bias": rendered["bias"],
                "RMSE": rendered["RMSE"],
                "mean s.e.": rendered["mean s.e."],
                "size": row.get("empirical_size", ""),
                "coverage": rendered["coverage"],
                "R": rendered["R"],
            }
        out.append(rendered)
    return out


def write_journal_tables(items):
    os.makedirs(OUT, exist_ok=True)
    perf, missing = main_performance_rows(items)
    rank = rank_frequency_rows(items)
    folds = fold_retention_rows(items)
    coeff = coeff_summary_rows(items)

    perf_fields = [
        "DGP", "target", "T", "N", "true_value", "mean_estimate", "bias", "rmse",
        "se_type", "mean_se", "empirical_size", "size_mcse", "coverage",
        "coverage_mcse", "replications",
    ]
    rank_fields = [
        "DGP", "T", "N", "J_min", "kappa_c", "retained_nonvalidation",
        "p_correct_rank", "p_underfit", "p_overfit", "modal_selected_rank",
        "replications",
    ]
    fold_fields = [
        "DGP", "N", "T", "q_T", "r_N", "h_N", "J_min", "realized_J",
        "retained_nonvalidation", "retained_total",
    ]
    coeff_fields = [
        "DGP", "N", "T", "mean(a_it)", "sd(a_it)", "min(a_it)", "max(a_it)",
        "max |a_it|", "mean(beta_it)", "sd(beta_it)", "min(beta_it)",
        "max(beta_it)", "mean PR2", "sd PR2", "c_xi", "R",
    ]

    _write_csv(os.path.join(OUT, "tab_mc_performance.csv"), perf, perf_fields)
    _write_csv(os.path.join(OUT, "tab_rank_frequency.csv"), rank, rank_fields)
    _write_csv(os.path.join(OUT, "tab_fold_retention.csv"), folds, fold_fields)
    _write_csv(os.path.join(OUT, "tab_mc_coeff_summary.csv"), coeff, coeff_fields)

    perf_main = _render_performance_rows(perf, include_size=False)
    perf_main_fields = [
        "DGP", "target", "N", "T", "true", "mean estimate", "bias",
        "RMSE", "mean s.e.", "coverage", "R",
    ]
    perf_full = _render_performance_rows(perf, include_size=True)
    perf_full_fields = [
        "DGP", "target", "N", "T", "true", "mean estimate", "bias",
        "RMSE", "mean s.e.", "size", "coverage", "R",
    ]

    _write_tex(
        os.path.join(OUT, "tab_mc_performance_current.tex"),
        perf_main,
        perf_main_fields,
        "llrrrrrrrrr",
        MAIN_PERFORMANCE_TABLE_NOTE,
    )
    _write_tex(
        os.path.join(OUT, "tab_mc_performance_full.tex"),
        perf_full,
        perf_full_fields,
        "llrrrrrrrrrr",
        FULL_PERFORMANCE_TABLE_NOTE,
    )
    _write_tex(os.path.join(OUT, "tab_rank_frequency.tex"), rank, rank_fields, "lrrrrrrrrlr")
    _write_tex(
        os.path.join(OUT, "tab_mc_coeff_summary.tex"),
        coeff,
        coeff_fields,
        "lrrrrrrrrrrrrrrr",
        "Coefficient and signal summaries are computed over Monte Carlo replications when the JSONL records contain DGP diagnostics. Older completed runs that predate these per-replication diagnostics leave the corresponding entries blank.",
    )
    _write_fold_retention_tex(os.path.join(OUT, "tab_fold_retention.tex"), folds)
    return {"performance": perf, "rank": rank, "folds": folds, "coeff": coeff, "missing": missing}


def main():
    items, load_missing = _load_grid_aggs()
    if not items:
        print("no grid*.jsonl files found in outputs/sim/")
        return
    result = write_journal_tables(items)
    for name in (
        "tab_mc_performance.csv",
        "tab_mc_performance_current.tex",
        "tab_mc_performance_full.tex",
        "tab_rank_frequency.csv",
        "tab_rank_frequency.tex",
        "tab_mc_coeff_summary.csv",
        "tab_mc_coeff_summary.tex",
        "tab_fold_retention.csv",
        "tab_fold_retention.tex",
    ):
        print(f"wrote {os.path.join(OUT, name)}")
    if load_missing:
        print(f"skipped {len(load_missing)} unreadable grid file(s)")
    if result["missing"]:
        print(f"missing numeric fields in {len(result['missing'])} table cell(s); see old-schema inputs")
    print(f"grid aggregates reported: {len(items)}")


if __name__ == "__main__":
    main()
